language: python
cache: pip
python:
  - "3.5"
  - "3.6"
script:
  - python setup.py test
  - python setup.py install
  - python -c "import klocmod; print(klocmod.__version__)"
  - python setup.py bdist_wheel
deploy:
  provider: pypi
  user: kozalo
  password:
    secure: Fn78i724u1Gd1f7t7hvnm+JK3+zFHhi3r7ayk5dJNh3c7qRp7+p3cu0UIfhDcOEhY/sGvuuiBiigvRxqr4kQK8VD2ZBPaUAtrn2+4EFqN5jqOqzQ3R3OQFinUWFWiPvboEfWH5nm0enVQ/XXCyWenQjm3ygPP390M7QG2SOHSq9uICRpZuXS9fAiUtGgoQhj0IPQE13zYOuPLpbcWYX4X0yrW82iGGTlhQo7iNBK26bQ9D1023NW6ANuh5vOX0ybDmYE3iMuwzA1N3HvGo2X2Z4WJoc0wmW32/2mmF5GRlnhnavcbuAx5KkN6wLtkkMkvWEMhW4OsS7bQ0gXAKfQP4KvCMgfuGkq5C+cHGHWS5ZM6HbIqG8CXx727d3CvO1EDQJIBDqm/pU6N9UbRaNhXlBRpzyPJLbZeVrTJKez7B0E2IapNfB81+ALJ1JhOjBzSwbMDWJ6EK8Dht+36w/xGjkAAqMH8zsRBn9OudvrZK9BEkFMRI9qupy/tPsSgOwi/DYZRdLT+lJ9ZZLRmNmNeen43WAuneA3mrY7TbmhE/PpWo7UpMUYTOxI0igXl69/fKJ/i26Mk75k4HJXK38cLXXTePd5sAdSNLVaovvJsEIsbkFViUtsCjFPeUIOSbX6FYNgfOwW9H0DAn4lnvJE0vNDjO9Tfd4EJTN4uSTndfc=
  on:
    tags: true
  distributions: sdist bdist_wheel
