language: python
cache: pip
python:
  - "3.5"
  - "3.6"
script:
  - python setup.py test
  - python setup.py install
  - python tests/ci_test_extras.py not installed
  - pip install PyYAML
  - python setup.py test
  - python tests/ci_test_extras.py installed
  - python setup.py sdist bdist_wheel
